# restart jekyll to see changes
# Site settings
title: Jonas Siedentop
subtitle: Tandemflüge in Franken
description: > # this means to ignore newlines until "baseurl:"
  Buche bei mir einen Gleitschirm Tandemflug und erlebe unser wunderschönes Franken aus einer ganz 
  neuen Perspektive. Das perfekte kleine Abenteuer für dich oder als Geschenk für deine Liebsten.
#baseurl: "/tandem-siedentop/" # the subpath of your site, e.g. /blog/
baseurl: ""
url: "" # the base hostname & protocol for your site

# User setting
owner: Jonas Siedentop
email: tandem@sieden.top
instagram: fliegerjonas
address:
  - line: Jonas Siedentop
  - line: Pegnitzstr. 31
  - line: D-90762 Fürth
  - line: Deutschland

collections:
  - locations


  # Feel free to add more lines here
telephone: +49 911 14885236
copyright: Jonas Siedentop

# Build settings
markdown: kramdown
